# Generated by Django 2.2.6 on 2021-08-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
