# Generated by Django 2.2.6 on 2021-08-09 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_auto_20210807_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservatio_date', models.DateField()),
                ('comment', models.CharField(max_length=1024)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.ConfRoom')),
            ],
        ),
    ]
