# Generated by Django 2.2.6 on 2021-08-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_roomreservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomreservation',
            old_name='reservatio_date',
            new_name='reservation_date',
        ),
        migrations.AlterUniqueTogether(
            name='roomreservation',
            unique_together={('reservation_date', 'room_id')},
        ),
    ]
